### ISSUE TITLE
On-prem helm install cnvrgio not creating the istio service

### ISSUE THREAD

**Issue by Y-Tian** [AccessibleAI/cnvrgio-operator#10]
I followed the instructions in the docs for an on-prem deployment of cnvrgio and the instructions were:

```
helm install cnvrg cnvrg/cnvrg --timeout 1500s  --wait \
    --set global.external_ip=<ip_of_cluster> \
	--set global.domain=<your_domain> \
    --set global.use_istio_ingress=true
```

However, the istio service never shows up or is created:
```
kubectl -n cnvrg get svc
NAME            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
app             ClusterIP   10.233.49.208   <none>        80/TCP     3m43s
elasticsearch   ClusterIP   10.233.34.141   <none>        9200/TCP   3m39s
minio           ClusterIP   10.233.27.51    <none>        80/TCP     3m33s
postgres        ClusterIP   10.233.7.254    <none>        5432/TCP   3m49s
redis           ClusterIP   10.233.5.174    <none>        6379/TCP   3m41s
```

I went ahead and deleted all pre-existing istio related kubenetes objects (configmap, clusterrole, clusterrolebindings), but it still won't get created.

Any help is appreciated.

**Comment by Dimss** [comment]
@Y-Tian the `cnvrg/cnvrg` chart base deployment (the one that you are trying to use) is deprecated. 
please refer to this [docs](https://app.cnvrg.io/docs/guides/operator.html) and [this docs](https://github.com/AccessibleAI/cnvrgio-operator#deploy-onprem--nodeport-minio-nfs) in order to deploy cnvrg with the operator.

**Comment by Y-Tian** [comment]
Sorry, let me clarify that I also tried deployed with: `helm install cnvrg cnvrg/cnvrgio --timeout 1500s  --wait \
    --set clusterDomain=<ip-of-cluster>`.

It looks like the Istio ingress should be used by default, but the service itself just never shows up. Has anyone run into this? Perhaps there's some sort of kubernetes object preventing istio from starting up?

**Comment by Dimss** [comment]
if you are running on-prem cluster and you do not have MetaLB (or any similar solution for creating LoadBalancer type K8S service) you'll have specify the IP address for istio to use for ingress service, by `--set istio.ingressIp=<ip-of-your-master>;<ip-of-you-node>;etc...`
Also, to see the deployment status, you can run `kubectl describe cnvrgapp cnvrg-app -n cnvrg` and check the status field.
